### ISSUE TITLE
uratalenが13じゃなくて16

### ISSUE THREAD

**Issue by terasawa** [eisoku9618/kuroiwa_demos#50]
そもそも管理者が管理しきれていない気がする

**Comment by eisoku9618** [comment]
@terasawa 

こちら解決した＋プロットまでの速度が2倍早くなったので，
`git clone https://github.com/eisoku9618/kuroiwa_demos.git -b do-not-use-buton`して使ってみてください．
この前はyamlをコメントイン・コメントアウトしつつ使っていたと思うけど，全部コメントインした上で，右クリック -> Hide -> hide this rowみたいな感じで，注目したいプロットだけにすることもできるようになりました．

※ https://github.com/eisoku9618/kuroiwa_demos/issues/51 は直していないので，st_qをel_qにして使ってください．
